MODEL:
  TYPE: duomamba
  NAME: duomamba_small
  DUOMAMBA:
    DROP_PATH_RATE: 0.25
    EMBED_DIM: 64
    DEPTHS: [2, 5, 20, 6]
    NUM_HEADS: [4, 8, 16, 16]
    EXPAND: 2
    CHUNK_SIZE: 32
    MIXER_TYPES:
      - 'DuoScanMixer'
      - 'DuoScanMixer'
      - ['DuoScanMixer', 'DuoScanMixer', 'DuoScanMixer', 'DuoScanMixer', 'MHSA', 'DuoScanMixer', 'DuoScanMixer', 'DuoScanMixer', 'DuoScanMixer', 'MHSA', 'DuoScanMixer', 'DuoScanMixer', 'DuoScanMixer', 'DuoScanMixer', 'MHSA', 'DuoScanMixer', 'DuoScanMixer', 'DuoScanMixer', 'DuoScanMixer', 'MHSA']
      - 'MHSA'
    D_STATE: 16
    NGROUPS: 2
    MLP_RATIO: 4.0
    GATING: True
    LPU: True
    STEM_VER: 1
    DOWNSAMPLER_VER: 1

  DDP: 'torch'

TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  MESA: 1.5

# RTX 4090
# 40.9 M 7.19 GFLOPs 780 TP 2217 MB 84.7% Acc@1

DATA:
  BATCH_SIZE: 256

AMP_DTYPE: bf16
